[Port]
Name=PORT1
Enable=1
RepeatCount=2
Type="TCP"
#Host="192.168.11.47"
#Host="192.168.100.102"
Host="127.0.0.1"
Port=502
Timeout=2000


[Device1]
PortName=PORT1
Name=PLC1.1
EnableDevice=1
ModbusUnit=1
RestoreTimeout=10000
MaxReadCoils=2000
MaxWriteMultipleCoils=2000
MaxReadDiscreteInputs=2000
MaxReadInputRegisters=120
MaxReadHoldingRegisters=120
MaxWriteMultipleRegisters=120
DefaultPeriod=500
RequestTimeout=5000

itemfile=PLC.csv

[Device2]
PortName=PORT1
Name=PLC1.2
EnableDevice=1
ModbusUnit=2
RestoreTimeout=10000
MaxReadCoils=2000
MaxWriteMultipleCoils=2000
MaxReadDiscreteInputs=2000
MaxReadInputRegisters=120
MaxReadHoldingRegisters=120
MaxWriteMultipleRegisters=120
DefaultPeriod=500
RequestTimeout=5000

itemfile=PLC.csv
