[Port]
Name=PORT2
Enable=1
RepeatCount=2
Type="TCP"
#Host="192.168.11.47"
#Host="192.168.100.102"
Host="127.0.0.1"
Port=503
Timeout=2000


[Device]
PortName=PORT2
Name=PLC2
EnableDevice=1
ModbusUnit=1
RestoreTimeout=10000
MaxReadCoils=2000,
MaxWriteMultipleCoils=2000
MaxReadDiscreteInputs=2000
MaxReadInputRegisters=120
MaxReadHoldingRegisters=120
MaxWriteMultipleRegisters=120
DefaultPeriod=500
RequestTimeout=5000

itemfile=PLC.csv

Log.flags="Error|Warning|Item"
Log.file.path="PLC2_LOG.csv"
#Log.file.maxcount=1
Log.file.format="%cat;%time;%src;%text"
Log.file.timeformat="%h:%m:%s.%f"
