[Port]
Name=PORT3
Enable=1
RepeatCount=2
Type="TCP"
#Host="192.168.11.47"
#Host="192.168.100.102"
Host="192.168.1.101"
#Host="127.0.0.1"
Port=504
Timeout=2000

Log.flags=Error|Warning|Info|Trace|TraceDetails|CtorDtor|EntryExit|ThreadStartStop|Connection|Item|Message|Protocol|Receive|Send
Log.file.format="%cat;%time;%src;%text"
Log.file.timeformat="%h:%m:%s.%f"
Log.file.path="PORT3_LOG.csv"
Log.output="file"

[Device]
PortName=PORT3
Name=PLC3
EnableDevice=1
ModbusUnit=3
RestoreTimeout=10000
MaxReadCoils=2000
MaxWriteMultipleCoils=2000
MaxReadDiscreteInputs=2000
MaxReadInputRegisters=120
MaxReadHoldingRegisters=120
MaxWriteMultipleRegisters=120
DefaultPeriod=500
RequestTimeout=5000

itemfile=PLC.csv

Log.flags="Error|Warning|Info|Trace|TraceDetails"
Log.file.path="PLC3_LOG.csv"
Log.file.maxcount=1
