[Project]
Name=test#test comment
#Log.flags=Error|Warning|Info|Trace|TraceDetails|CtorDtor|EntryExit|ThreadStartStop|Connection|Item|Message|Protocol|Receive|Send           
Log.flags="Error|Warning|Info|TraceDetails"

Log.output="system file console"
Log.default.format="[%time] %src. %text"
Log.default.timeformat="%Y-%M-%D %h:%m:%s.%f"
#Log.system.format=""
#Log.system.timeformat=""
#Log.concole.format=""
#Log.console.timeformat=""
Log.file.format="%time;%cat;%src;%text"
Log.file.timeformat="%h:%m:%s.%f"
Log.file.path="log.csv"
# Setting for log file rotation:
# * maxcount - max count of files
# * maxsize - max file size in bytes
Log.file.maxcount=10
Log.file.maxsize=1000000

#include="PLC1.conf"          
#include="PLC2.conf"          
#include="PLC3.conf"          

[OPCUA]

#Port=4840
UncertainAs=Good#Bad#Good#Uncertain

[Port]
Name=PORT1
Enable=1
RepeatCount=2
Type=TCP
Host="127.0.0.1"
Port=502
Timeout=2000

[Device]
PortName=PORT1
Name=PLC1
EnableDevice=1
ModbusUnit=1
RestoreTimeout=10000
MaxReadCoils=2000,
MaxWriteMultipleCoils=2000
MaxReadDiscreteInputs=2000
MaxReadInputRegisters=120
MaxReadHoldingRegisters=120
MaxWriteMultipleRegisters=120
DefaultPeriod=500
RequestTimeout=5000

#itemfile=PLC.csv

i:Test_Int16     ="400001 S"
i:Test_UInt16    ="400001 R"
i:Test_Int32     ="400001 I"
i:Test_UInt32    ="400001 U"
i:Test_Int64     ="400001 LL"
i:Test_UInt64    ="400001 UL"
i:Test_Float     ="400001 F"
i:Test_Double    ="400001 LF"
i:Test_SwInt32   ="400001 IS"
i:Test_SwUInt32  ="400001 US"
i:Test_SwInt64   ="400001 LLS,2000"
i:Test_SwUInt64  ="400001 ULS,2000"
i:Test_SwFloat   ="400001 FS"
i:Test_SwDouble  ="400001 LFS"
i:Test_ByteArray ="400001-400010 B"
