# - is_linux_family(familyname)
#   Returns TRUE if the current Linux distro belongs to the specified family (e.g., debian, fedora, arch)
#   Usage: is_linux_family("debian" IS_DEBIAN_LIKE)
#
function(is_linux_family familyname result)
    set(_res FALSE)
    if(EXISTS "/etc/os-release")
        file(READ "/etc/os-release" _os_release_content)
		string(REGEX MATCH "(^|\n)ID=([^\n]*)" _id_match "${_os_release_content}")
		if(_id_match MATCHES "${familyname}")
			set(_res TRUE)
		else()
			string(REGEX MATCH "(^|\n)ID_LIKE=([^\n]*)" _id_like_match "${_os_release_content}")
			if(_id_like_match MATCHES "${familyname}")
				set(_res TRUE)
			endif()
        endif()
    endif()
    set(${result} ${_res} PARENT_SCOPE)
endfunction()
