#!/bin/bash

# set -e is used in shell scripts to make the script exit immediately
# if any command returns a non-zero (error) status
set -e

if [ "$1" = "configure" ]; then
    # Run install service script after installation
    @CN_APP_NAME@s.sh --install
fi