#!/bin/bash

# set -e is used in shell scripts to make the script exit immediately
# if any command returns a non-zero (error) status
set -e

#if [ "$1" = "configure" ]; then
#	# Enable and start the modbusua service after installation
#    systemctl enable @CN_APP_NAME@
#    systemctl start @CN_APP_NAME@
#fi