#!/bin/bash

# set -e is used in shell scripts to make the script exit immediately
# if any command returns a non-zero (error) status
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    # Run uninstall service script before uninstallation
    @CN_APP_NAME@s.sh --uninstall
fi
